<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Deleuze.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- ASP.NET Core の共通機能（HttpContext, Authenticationハンドラー等）を利用可能にする -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- JWT Bearer 認証機能用パッケージ -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    <!-- ProvisioningとMigrationをSharedに共通化 -->
    <PackageReference Include="Npgsql" Version="8.0.2" />
    <!-- Swagger UI / OpenAPI 共通処理用パッケージ -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>